# Generated by Django 4.2.3 on 2023-08-06 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lodging', '0002_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgingscrap',
            name='lodging',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodgingScrap', to='lodging.lodgingmain'),
        ),
        migrations.AlterField(
            model_name='lodgingscrap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userLodging', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='priceByDate',
        ),
    ]
