# Generated by Django 4.2.3 on 2023-08-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0002_alter_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodgingmain',
            name='scrap',
        ),
    ]
