# Generated by Django 4.2.3 on 2023-08-06 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0003_alter_lodgingscrap_lodging_alter_lodgingscrap_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgingscrap',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
