# Generated by Django 4.2.3 on 2023-08-11 16:02

from django.db import migrations, models
import lodging.models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0005_remove_lodgingscrap_createdat_review_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(null=True, upload_to=lodging.models.lodging_review_photo_path),
        ),
    ]
