# Generated by Django 4.2.3 on 2023-08-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodging', '0006_alter_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodgingmain',
            name='price',
        ),
        migrations.AddField(
            model_name='lodgingmain',
            name='lowWeekdayPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lodgingmain',
            name='lowWeekendPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lodgingmain',
            name='peakWeekdayPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lodgingmain',
            name='peakWeekendPrice',
            field=models.IntegerField(default=0),
        ),
    ]
