# Generated by Django 4.2.3 on 2023-08-05 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recreation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recreationscrap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRecreation', to=settings.AUTH_USER_MODEL),
        ),
    ]
