# Generated by Django 4.2.3 on 2023-08-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recreation', '0002_alter_recreationscrap_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recreationscrap',
            old_name='scrap',
            new_name='isScrap',
        ),
        migrations.RemoveField(
            model_name='recreationmain',
            name='scrap',
        ),
    ]
